### PR TITLE
Slowdown

### LINKED ISSUE #22: Time Slow Down

### LINKED ISSUE #109: Time Slow Down UI

### PR DESCRIPTION
**Pull request by HassanAbusalih**
Closes #22 
Closes #109 

Everything viewable in the SlowdownTesting scene.

I was gonna do my usual thing of sitting on a completed task for a bit in case I get any new ideas, but this mechanic is so straightforward that that's not very likely to happen. 

In terms of the logic here, there's a configurable activation cooldown to stop the player from spamming the ability, and there's another separate cooldown if you use all segments - that one lasts until the first segment is recharged. Everything else is self explanatory I think.

I expect some bugs to crop up down the line cuz this is untested with all the other systems besides telekinesis (which did have a bug, though unrelated) 😄 

I will say, the drop in the jump feels a little bit odd during slowdown. I'm pretty sure it's not behaving differently, it's just easier to notice the moment when you start dropping vs the floatiness before that.

### CODE REVIEW

**Review by avinash751 — APPROVED** [review]
slow down implementation is really nicely done, like daaamn the slow down is soooooo smooth. i get what you mean by the jump looking off in slow down , it mainly looks like the gravity is still very sensitive in slow down, i tried different updates, that did not work, well for now its not really a major issue, so we can look into that later. 

Also in the code you are modifying the fixeddeltaTime , is that how you achieve slow down so smooth, because i know just changing timescale directly  does not give this smooth slow down. 

but yeah nice work man ME APPROVE

**Review by Armaantakyar1 — CHANGES_REQUESTED** [review]
the implementation is great and plays well but I found a big bug with the game manager where the player can use the slowdown and make the game unpaused this needs to fixed before we merge I have put the video in the discord thread

**Review by somnolentz — CHANGES_REQUESTED** [review]
Overall it feels super smooth, me likey
but some concerns: 
-as armaan mentioned, it interferes with the game manager due to timescale
-i see youre using a courotine; if im not mistaken wouldnt this be frame reliant, leading to the same issue we had with dash in dreadrun? correct me if im wrong/im missing sth and you already took that into account. maybe test it out with build versions with diff fps caps if you havent before we merge
otherwise gud job :>

**Review by devTrivedi1 — APPROVED** [review]
Overall nicely done, feels smooth to use too 
I will need to probably check later in a build version with a timer and check how it runs on each FPS (dreadrun dash flashbacks) but yeh, looks good so far

**Comment by HassanAbusalih** [comment]
> Overall it feels super smooth, me likey
> but some concerns: 
> -as armaan mentioned, it interferes with the game manager due to timescale
> -i see youre using a courotine; if im not mistaken wouldnt this be frame reliant, leading to the same issue we had with dash in dreadrun? correct me if im wrong/im missing sth and you already took that into account. maybe test it out with build versions with diff fps caps if you havent before we merge
> otherwise gud job :>

I'm incrementing using delta time and lerping based on that - this is how stuff is made to not be framerate dependant in general, coroutine or not. The number of frames is irrelevant because I'm measuring using time. Can you explain why this wouldn't be the case?

**Pull request merged**
