### PR TITLE
Chain throwable

### LINKED ISSUE #99: Shrapnel Ricochet boomerang Throwable

### PR DESCRIPTION
**Pull request by HassanAbusalih**
Works in build, viewable in the TelekinesisTesting scene. Closes #99 

### Code

It's a recursive coroutine (@somnolentz 's nightmare) with a delay at the end, so the chains happen in batches. It spawns a line renderer that connects the origin and target, then after a delay, it shrinks the width of the line to 0 then destroys it. 

Coroutine workhorse is getting some serious work done here, cuz it's not possible to run the coroutines on the telekinetic object since it's getting disabled.

### VFX

I was really going crazy with all the different stuff I tried. I ended up making a shader graph based on something I saw in a vfx graph tutorial, and yoinked the impact off of good ol' reliable Hovl Studio we used last tri. I made one myself, but it just looked worse.

### CODE REVIEW

**Review by avinash751 — APPROVED** [review]
Code is really good , definitely a unique way to do recursion with the use of events. very nice stuff. the vfx is also really good. 

if we were to do polish, i would add a shake to the object  getting electrocuted before it adds force and maybe the shader can go along with having  some spark particles along with color pulsate in the shader . this is just  future suggestions.

my one concern is the use of coroutines , i have nothing against using the workhorse, its just that in dread run the jump and camera trigger uses coroutine and they act different in different frame rates, since coroutines are frame rate dependent . so that is something that needs to be tested  in different hardwares for this game as well to see how it looks and feels. its just a concern nothing else

**Comment by avinash751** [comment]
one thing can you put the reseter in the ref manager so we get reference from there

**Comment by HassanAbusalih** [comment]
> my one concern is the use of coroutines , i have nothing against using the workhorse, its just that in dread run the jump and camera trigger uses coroutine and they act different in different frame rates, since coroutines are frame rate dependent . so that is something that needs to be tested in different hardwares for this game as well to see how it looks and feels. its just a concern nothing else

# THIS IS FAKE NEWS. 

There's nothing about coroutines that makes them framerate dependent any more than Update is framerate dependent. Even WaitForSeconds is affected by timescale so it's not framerate dependent either.

**Review by Armaantakyar1 — APPROVED** [review]
looks good to me gg

**Pull request merged**
